name: Manel López Torrent
bio: 'Project Manager and Agile Web Developer'
picture: 'assets/images/profile.jpg'

url: http://malotor.github.io
# your url: http://USERNAME.github.io/
permalink: /:title/

analytics: 'UA-MYANALYTICS'
disqus: mydisqus
twitter: mloptor
linkedin: in/manuellopeztorrent
github: malotor
email: malotor@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
